spring:
  application:
    name: edit
  profiles:
    active: dev

ses:
  email: hr.seongeun@gmail.com
  access-key: AKIAJKTMKM4CXTVZXKSA
  secret-key: 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
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: hr.seongeun@gmail.com
#    password: tnfrbnwdyriduulq
#    properties:
#      mail:
#        smtp:
#          timeout: 5000
#          auth: true
#          starttls:
#            enable: true