cloud:
  aws:
    credentials:
      accessKey: AKIAT3HDLPKJPLU6URMX
      secretKey: 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
    s3:
      bucket: edit-server-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

ses:
  email: hr.seongeun@gmail.com
  access-key: AKIAJKTMKM4CXTVZXKSA
  secret-key: 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
