spring:
  application:
    name: edit
  profiles:
    include: credentials
    active: prod


#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: hr.seongeun@gmail.com
#    password: tnfrbnwdyriduulq
#    properties:
#      mail:
#        smtp:
#          timeout: 5000
#          auth: true
#          starttls:
#            enable: true