cloud:
  aws:
    credentials:
      accessKey: AKIAT3HDLPKJPLU6URMX
      secretKey: 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
    s3:
      bucket: edit-server-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
